export const SET_WEATHER = "SET_WEATHER";
export const FETCH_WEATHER_FAIL = "FETCH_WEATHER_FAIL";
export const SET_WEATHER_DAILY = "SET_WEATHER_DAILY";

export const CHANGE_TEMP_SELECTION_DAILY = "CHANGE_TEMP_SELECTION_DAILY";
export const CHANGE_TEMP_SELECTION_MONTHLY = "CHANGE_TEMP_SELECTION_MONTHLY";
export const CHANGE_TEMP_SELECTION_REALTIME = "CHANGE_TEMP_SELECTION_REALTIME";
export const CHANGE_HUMI_SELECTION_DAILY = "CHANGE_HUMI_SELECTION_DAILY";
export const CHANGE_HUMI_SELECTION_MONTHLY = "CHANGE_HUMI_SELECTION_MONTHLY";
export const CHANGE_HUMI_SELECTION_REALTIME = "CHANGE_HUMI_SELECTION_REALTIME";

